#include "pch.h"
#include "CWin32SoftwareLicensingProduct.h"

const char* CWin32SoftwareLicensingProductObject::ObjectName = "SoftwareLicensingProduct";

const char* CWin32SoftwareLicensingProductObject::propertyNames[] =
{
    "ID",
    "Name",
    "Description",
    "ApplicationID",
    "ProcessorURL",
    "MachineURL",
    "ProductKeyURL",
    "UseLicenseURL",
    "LicenseStatus",
    "LicenseStatusReason",
    "GracePeriodRemaining",
    "EvaluationEndDate",
    "OfflineInstallationId",
    "PartialProductKey",
    "ProductKeyID",
    "LicenseFamily",
    "LicenseDependsOn",
    "LicenseIsAddon",
    "VLActivationInterval",
    "VLRenewalInterval",
    "KeyManagementServiceProductKeyID",
    "KeyManagementServiceMachine",
    "KeyManagementServicePort",
    "DiscoveredKeyManagementServiceMachineName",
    "DiscoveredKeyManagementServiceMachinePort",
    "IsKeyManagementServiceMachine",
    "KeyManagementServiceCurrentCount",
    "RequiredClientCount",
    "KeyManagementServiceUnlicensedRequests",
    "KeyManagementServiceLicensedRequests",
    "KeyManagementServiceOOBGraceRequests",
    "KeyManagementServiceOOTGraceRequests",
    "KeyManagementServiceNonGenuineGraceRequests",
    "KeyManagementServiceTotalRequests",
    "KeyManagementServiceFailedRequests",
    "KeyManagementServiceNotificationRequests",
    "GenuineStatus",
    "ExtendedGrace",
    "TokenActivationILID",
    "TokenActivationILVID",
    "TokenActivationGrantNumber",
    "TokenActivationCertificateThumbprint",
    "TokenActivationAdditionalInfo",
    "TrustedTime",
    NULL
};
